<h1 class="page-header">Flux d'activités</h1>

<ul class="media-list">
    <li class="media">
        <div class="media-body">
            <div class="media">
                <p>
                    <span class="label label-important">VIVAMUS</span> : Vivamus eleifend velit eu magna condimentum pellentesque. Integer tempus mi at turpis pellentesque feugiat consectetur nunc facilisis. Duis aliquam tellus et massa ultrices rhoncus. Vivamus eleifend velit eu magna condimentum pellentesque.<br>
                    <small><a href="">Voir le détail</a> - <a href="">Contacter le sdis</a> - <span class="muted">le 00/00/0000 à 00:00</span></small>
                </p>
            </div>
        </div>
    </li>       
    <li class="media">
        <div class="media-body">
            <div class="media">
                <p>
                    <span class="label ">VIVAMUS</span> : Vivamus eleifend velit eu magna condimentum pellentesque. Integer tempus mi at turpis pellentesque feugiat consectetur nunc facilisis. Duis aliquam tellus et massa ultrices rhoncus. Vivamus eleifend velit eu magna condimentum pellentesque.<br>
                    <small><a href="">Voir le détail</a> - <a href="">Contacter le sdis</a> - <span class="muted">le 00/00/0000 à 00:00</span></small>
                </p>
            </div>
        </div>
    </li>
    <li class="media">
        <div class="media-body">
            <div class="media">
                <p>
                    <span class="label label-important">VIVAMUS</span> : Vivamus eleifend velit eu magna condimentum pellentesque. Integer tempus mi at turpis pellentesque feugiat consectetur nunc facilisis. Duis aliquam tellus et massa ultrices rhoncus. Vivamus eleifend velit eu magna condimentum pellentesque.<br>
                    <small><a href="">Voir le détail</a> - <a href="">Contacter le sdis</a> - <span class="muted">le 00/00/0000 à 00:00</span></small>
                </p>
            </div>
        </div>
    </li>
    <li class="media">
        <div class="media-body">
            <div class="media">
                <p>
                    <span class="label">VIVAMUS</span> : Vivamus eleifend velit eu magna condimentum pellentesque. Integer tempus mi at turpis pellentesque feugiat consectetur nunc facilisis. Duis aliquam tellus et massa ultrices rhoncus. Vivamus eleifend velit eu magna condimentum pellentesque.<br>
                    <small><a href="">Voir le détail</a> - <a href="">Contacter le sdis</a> - <span class="muted">le 00/00/0000 à 00:00</span></small>
                </p>
            </div>
        </div>
    </li>
    <li class="media">
        <div class="media-body">
            <div class="media">
                <p>
                    <span class="label">VIVAMUS</span> : Vivamus eleifend velit eu magna condimentum pellentesque. Integer tempus mi at turpis pellentesque feugiat consectetur nunc facilisis. Duis aliquam tellus et massa ultrices rhoncus. Vivamus eleifend velit eu magna condimentum pellentesque.<br>
                    <small><a href="">Voir le détail</a> - <a href="">Contacter le sdis</a> - <span class="muted">le 00/00/0000 à 00:00</span></small>
                </p>
            </div>
        </div>
    </li><li class="media">
        <div class="media-body">
            <div class="media">
                <p>
                    <span class="label">VIVAMUS</span> : Vivamus eleifend velit eu magna condimentum pellentesque. Integer tempus mi at turpis pellentesque feugiat consectetur nunc facilisis. Duis aliquam tellus et massa ultrices rhoncus. Vivamus eleifend velit eu magna condimentum pellentesque.<br>
                    <small><a href="">Voir le détail</a> - <a href="">Contacter le sdis</a> - <span class="muted">le 00/00/0000 à 00:00</span></small>
                </p>
            </div>
        </div>
    </li><li class="media">
        <div class="media-body">
            <div class="media">
                <p>
                    <span class="label label-important">VIVAMUS</span> : Vivamus eleifend velit eu magna condimentum pellentesque. Integer tempus mi at turpis pellentesque feugiat consectetur nunc facilisis. Duis aliquam tellus et massa ultrices rhoncus. Vivamus eleifend velit eu magna condimentum pellentesque.<br>
                    <small><a href="">Voir le détail</a> - <a href="">Contacter le sdis</a> - <span class="muted">le 00/00/0000 à 00:00</span></small>
                </p>
            </div>
        </div>
    </li>
    <li class="media">
        <div class="media-body">
            <div class="media">
                <p>
                    <span class="label label-important">VIVAMUS</span> : Vivamus eleifend velit eu magna condimentum pellentesque. Integer tempus mi at turpis pellentesque feugiat consectetur nunc facilisis. Duis aliquam tellus et massa ultrices rhoncus. Vivamus eleifend velit eu magna condimentum pellentesque.<br>
                    <small><a href="">Voir le détail</a> - <a href="">Contacter le sdis</a> - <span class="muted">le 00/00/0000 à 00:00</span></small>
                </p>
            </div>
        </div>
    </li>
    <li class="media">
        <div class="media-body">
            <div class="media">
                <p>
                    <span class="label">VIVAMUS</span> : Vivamus eleifend velit eu magna condimentum pellentesque. Integer tempus mi at turpis pellentesque feugiat consectetur nunc facilisis. Duis aliquam tellus et massa ultrices rhoncus. Vivamus eleifend velit eu magna condimentum pellentesque.<br>
                    <small><a href="">Voir le détail</a> - <a href="">Contacter le sdis</a> - <span class="muted">le 00/00/0000 à 00:00</span></small>
                </p>
            </div>
        </div>
    </li>
    <li class="media">
        <div class="media-body">
            <div class="media">
                <p>
                    <span class="label label-important">VIVAMUS</span> : Vivamus eleifend velit eu magna condimentum pellentesque. Integer tempus mi at turpis pellentesque feugiat consectetur nunc facilisis. Duis aliquam tellus et massa ultrices rhoncus. Vivamus eleifend velit eu magna condimentum pellentesque.<br>
                    <small><a href="">Voir le détail</a> - <a href="">Contacter le sdis</a> - <span class="muted">le 00/00/0000 à 00:00</span></small>
                </p>
            </div>
        </div>
    </li>
</ul>