<h1 class="page-header">Gestion des utilisateurs</h1>

<div class="row">

    <div class="span4">
    
    <ul class="nav nav-list">
        <li class="nav-header">Liste des utilisateurs</li>
        <li class="active"><a href="#">Voir tout</a></li>
        <li class="nav-header">Actions sur la gestion des utilisateurs</li>
        <li><a href="#">Ajout d'un utilisateur</a></li>
        <li><a href="#">Gestion des droits d'accès aux applications</a></li>
    </ul>
        
    </div>
    
<div class="span8">

    <h2>Utilisateurs LDAP</h2>
    
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Nom</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>Michael</td>
                <td><a href="">Modifier</a></td>
            </tr>
            <tr>
                <td>2</td>
                <td>Jake</td>
                <td><a href="">Modifier</a></td>
            </tr>
        </tbody>
    </table>
        
    <h2>Utilisateurs en base de données</h2>
        
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Nom</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>Michael</td>
                <td><a href="">Modifier</a></td>
            </tr>
            <tr>
                <td>2</td>
                <td>Jake</td>
                <td><a href="">Modifier</a></td>
            </tr>
        </tbody>
    </table>
</div>