<h1 class="page-header">Gestion des utilisateurs</h1>

<div class="row">

    <div class="span3">
    
    <?php
        echo $this->navigation()->menu()
            ->setMinDepth(1)
            ->setMaxDepth(1)
            ->setUlClass("nav nav-list")
            ->setRenderParents(false)
            ->setOnlyActiveBranch(true)
            ->renderMenu($this->nav);
    ?>
        
    </div>
    
<div class="span9">

    <h2>Utilisateurs LDAP</h2>
    
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Nom</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>Michael</td>
                <td><a href="">Modifier</a></td>
            </tr>
            <tr>
                <td>2</td>
                <td>Jake</td>
                <td><a href="">Modifier</a></td>
            </tr>
        </tbody>
    </table>
        
    <h2>Utilisateurs en base de données</h2>
        
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Nom</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>Michael</td>
                <td><a href="">Modifier</a></td>
            </tr>
            <tr>
                <td>2</td>
                <td>Jake</td>
                <td><a href="">Modifier</a></td>
            </tr>
        </tbody>
    </table>
</div>