<h1 class="page-header">Gestion des applications</h1>

<div class="row">

    <div class="span3">
    
    <ul class="nav nav-list">
        <li class="nav-header">Liste des applications</li>
        <li class="active"><a href="#">Voir les applications</a></li>
        <li><a href="#">Voir les modules & bridges</a></li>
        <li class="nav-header">Actions sur les applications</li>
        <li><a href="#">Ajout d'une application</a></li>
    </ul>
        
    </div>
    
<div class="span9">

    <h2>Applications de l'écosystème SDIS 62</h2>
    
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Nom</th>
                <th>URL</th>
                <th>Statut</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>Prevarisc</td>
                <td><a href="">http://prevarisc.sdis62.fr</a></td>
                <td><span class="label label-success">Fonctionne</span></td>
                <td><a href="">Modifier</a></td>
            </tr>
            <tr>
                <td>1</td>
                <td>Prevarisc</td>
                <td><a href="">http://prevarisc.sdis62.fr</a></td>
                <td><span class="label label-success">Fonctionne</span></td>
                <td><a href="">Modifier</a></td>
            </tr>
            <tr>
                <td>1</td>
                <td>Prevarisc</td>
                <td><a href="">http://prevarisc.sdis62.fr</a></td>
                <td><span class="label label-important">Inaccessible</span></td>
                <td><a href="">Modifier</a></td>
            </tr>
            <tr>
                <td>1</td>
                <td>Prevarisc</td>
                <td><a href="">http://prevarisc.sdis62.fr</a></td>
                <td><span class="label label-success">Fonctionne</span></td>
                <td><a href="">Modifier</a></td>
            </tr>
        </tbody>
    </table>
    
    <h2>Applications du SDIS 62</h2>
    
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Nom</th>
                <th>URL</th>
                <th>Statut</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>Prevarisc</td>
                <td><a href="">http://prevarisc.sdis62.fr</a></td>
                <td><span class="label label-success">Fonctionne</span></td>
                <td><a href="">Modifier</a></td>
            </tr>
            <tr>
                <td>1</td>
                <td>Prevarisc</td>
                <td><a href="">http://prevarisc.sdis62.fr</a></td>
                <td><span class="label label-success">Fonctionne</span></td>
                <td><a href="">Modifier</a></td>
            </tr>
            <tr>
                <td>1</td>
                <td>Prevarisc</td>
                <td><a href="">http://prevarisc.sdis62.fr</a></td>
                <td><span class="label label-important">Inaccessible</span></td>
                <td><a href="">Modifier</a></td>
            </tr>
            <tr>
                <td>1</td>
                <td>Prevarisc</td>
                <td><a href="">http://prevarisc.sdis62.fr</a></td>
                <td><span class="label label-success">Fonctionne</span></td>
                <td><a href="">Modifier</a></td>
            </tr>
        </tbody>
    </table>
    
    <h2>Applications externes</h2>
    
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Nom</th>
                <th>URL</th>
                <th>Statut</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>Prevarisc</td>
                <td><a href="">http://prevarisc.sdis62.fr</a></td>
                <td><span class="label label-success">Fonctionne</span></td>
                <td><a href="">Modifier</a></td>
            </tr>
            <tr>
                <td>1</td>
                <td>Prevarisc</td>
                <td><a href="">http://prevarisc.sdis62.fr</a></td>
                <td><span class="label label-success">Fonctionne</span></td>
                <td><a href="">Modifier</a></td>
            </tr>
            <tr>
                <td>1</td>
                <td>Prevarisc</td>
                <td><a href="">http://prevarisc.sdis62.fr</a></td>
                <td><span class="label label-important">Inaccessible</span></td>
                <td><a href="">Modifier</a></td>
            </tr>
            <tr>
                <td>1</td>
                <td>Prevarisc</td>
                <td><a href="">http://prevarisc.sdis62.fr</a></td>
                <td><span class="label label-success">Fonctionne</span></td>
                <td><a href="">Modifier</a></td>
            </tr>
        </tbody>
    </table>

</div>