<?php if(count($this->groups) == 0) : ?>
<p class="muted">Il n'y a pas encore de groupes d'applications.</p>
<?php else : ?>
    <?php foreach($this->groups as $group) : ?>
    <h3>
        <span class="badge" style="background-color: <?php echo $this->escape($group->getColor()) ?>; font-size: 1em;">&nbsp;</span>
        <span><?php echo $this->escape($group->getName()) ?></span>
        <small><?php echo $this->escape(count($group->getApplications())) ?> application<?php echo $this->escape(count($group->getApplications())) > 1 ? "s" : ""?></small>
    </h3>
    <?php echo $this->partial("applications/partial_list_applications.phtml", array("applications" => $group->getApplications())) ?>
    <?php endforeach ?>
<?php endif ?>

<?php if(count($this->applications_without_group) != 0) : ?>
<hr/>
<h2>Les applications affectées à aucun groupe</h2>
<?php echo $this->partial("applications/partial_list_applications.phtml", array("applications" => $this->applications_without_group)) ?>
<?php endif ?>
<p class="muted"><small><u>Note:</u> Les statuts des applications sont actualisés toutes les minutes.</small></p>

<script>
    function updateApplicationsStatus() {
        $.get("<?php echo $this->url(array("action" => "get-applications-status")) ?>", null, function(data, textStatus, jqXHR) {
            for(var id in data) {
                var selector = $('*[data-application-id="' + id + '"]').find("span.status");
                selector.removeClass("label-success label-error label-warning");
                switch(data[id]) {
                    case "success":
                        selector.html("Fonctionne").addClass("label-success");
                        break;
                    case "inactive":
                        selector.html("Inactive");
                        break;
                    case "error":
                        selector.html("Inaccessible").addClass("label-error");
                        break;
                    default:
                        selector.html("Statut indéterminé").addClass("label-warning");
                        break;
                }
            }
        }, "json");
    }
    
    document.addEventListener("DOMContentLoaded", function() {
        updateApplicationsStatus();
        setInterval("updateApplicationsStatus();", 60000);
    }, false);
</script>