<!doctype html>
<html lang="fr" >
    <head>
        <meta charset="utf-8">
        
        <style>
          body {
            padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
          }
        </style>

        <?php echo $this->headMeta() ?>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>
        <?php echo $this->headScript() ?>
        
        

        <!--<script src="/js/libs/modernizr-2.5.3.min.js"></script>-->
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="#">Module utilisateur</a>
                    <div class="nav-collapse collapse">
                        <?php echo $this->navigation()->menu()->setMaxDepth(0)->setUlClass('nav'); ?>
                        <ul class="nav pull-right">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Kévin DUBUC <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Mon profil</a></li>
                                    <li><a href="#">Modifier mes informations</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">Deconnexion</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            <h1>Bootstrap starter template</h1>
            <?php echo $this->layout()->content ?>
        </div>

        
        
        <?php echo $this->inlineScript() ?>
    </body>
</html>