<!doctype html>
<html lang="fr" >

    <head>
        <meta charset="utf-8">
        
        <style>
          body {
            padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
          }
        </style>

        <?php echo $this->headMeta() ?>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>
        <?php echo $this->headScript() ?>

        <!--<script src="/js/libs/modernizr-2.5.3.min.js"></script>-->
    </head>
    
    <body>
    
        <!-- Nav bar -->
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="#">SDIS62 ID</a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <?php echo $this->partial("menu.phtml", array("page" => $this->navigation()->findOneById("home"))) ?>
                            <?php echo $this->partial("menu.phtml", array("page" => $this->navigation()->findOneById("applications"))) ?>
                        </ul>
                        
                            <?php
                            if(Zend_Auth::getInstance()->hasIdentity())
                            {
                                echo "<ul class=\"nav pull-right\">";
                                echo "<li class=\"dropdown\">";
                                echo "<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">" . Zend_Auth::getInstance()->getIdentity()->display_name . " <b class=\"caret\"></b></a>";
                                echo $this->navigation($this->navigation)
                                    ->menu($this->navigation()->findOneById('user'))
                                    ->setRenderParents(true)
                                    ->setUlClass('dropdown-menu');
                                 echo "</ul>";
                            }
                            else
                            {
                                echo "<ul class=\"nav pull-right\">";
                                echo $this->partial("menu.phtml", array("page" => $this->navigation()->findOneById("login")));
                                echo "</ul>";
                            }
                            ?>
                    </div>
                </div>
            </div>
        </div>

        <!-- Container -->
        <div class="container">
            <!-- Notifications -->
            <?php if( $this->flashMessenger()->hasMessages() ): ?>
                <ul id="flashmessenger" class="unstyled" >
                <?php echo $this->flashMessenger()->output(); ?>
                </ul>
            <?php endif ?>
            
            <!-- breadcrumb -->
            <?php echo $this->navigation()->breadcrumbs()->setPartial(array('breadcrumbs.phtml', 'default')); ?>
            
            <!-- Content -->
            <?php echo $this->layout()->content ?>
        </div>

        <!-- javascript (fast load)-->
        <?php echo $this->inlineScript() ?>
        
    </body>
    
</html>