<!doctype html>
<html lang="fr" >

    <head>
        <meta charset="utf-8">
        
        <style>
          body {
            padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
          }
        </style>

        <?php echo $this->headMeta() ?>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>
        <?php echo $this->headScript() ?>

        <script src="<?php echo ASSETS_PATH ?>components/modernizr/modernizr.js"></script>
    </head>
    
    <body>

        <!-- Container -->
        <div class="container container-primary">
        
            <!-- Nav bar -->
            <div class="navbar navbar-fixed-top">
                <div class="navbar-inner">
                    <div class="container">
                        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </a>
                        <ul class="nav">
                            <li class="logo"><img src="<?php echo ASSETS_PATH ?>components/sdis62-ui/img/logo_sdis_pastille.png" alt="SDIS 62" /></li>
                            <li class="divider-vertical"></li>
                            <li class="brand"><span style="color: #D01F3C">Command Center</span></li>
                        </ul>
                        <div class="nav-collapse collapse">
                            <?php
                                echo $this->navigation()
                                    ->menu()
                                    ->setUlClass('nav pull-right')
                                    ->setMaxDepth(-1)
                                    ->setMinDepth(0)
                                    ->setRenderParents(false)
                                    ->setOnlyActiveBranch(false)
                                    ->renderMenu($this->user_nav);
                            ?>
                        </div>
                    </div>
                </div>
            </div>
            
            <!-- Notifications -->
            <?php if( $this->flashMessenger()->hasMessages() ): ?>
                <ul id="flashmessenger" class="unstyled" >
                <?php echo $this->flashMessenger()->output(); ?>
                </ul>
            <?php endif ?>
            
            <!-- Barre de navigation -->
            <div class="navbar">
                <div class="navbar-inner">
                <?php
                echo $this->navigation()
                    ->menu()
                    ->setUlClass('nav nav-fluid')
                    ->setMaxDepth(0)
                    ->setMinDepth(0)
                    ->setRenderParents(false)
                    ->setOnlyActiveBranch(false)
                    ->renderMenu($this->nav);
                ?>
                </div>
            </div>

            <!-- breadcrumb -->
            <?php //echo $this->navigation()->breadcrumbs()->setPartial(array('breadcrumbs.phtml', 'default')); ?>
            
            <!-- Menu gauche -->
            <h1 class="page-header"><?php echo $this->navigation()->breadcrumbs()->setMinDepth(0)->setMaxDepth(0)->setPartial(null); ?></h1>

            <div class="row">

                <div class="span3">
                <?php
                    echo $this->navigation()->menu()
                        ->setMinDepth(1)
                        ->setMaxDepth(1)
                        ->setUlClass("nav nav-list")
                        ->setRenderParents(false)
                        ->setOnlyActiveBranch(true)
                        ->renderMenu($this->nav);
                ?>
                </div>
                
                <div class="span9">
                
                    <h2><?php echo $this->navigation()->findOneBy('active', true)->getLabel() ?></h2>
                    
                    <!-- Content -->
                    <?php echo $this->layout()->content ?>
                    
                </div>

            </div>
            
            <footer>
                <p>© SDIS 62 - 2013</p>
            </footer>

        </div>

        <!-- javascript (fast load)-->
        <?php echo $this->inlineScript() ?>
        
    </body>
    
</html>