<!doctype html>
<html lang="fr" >

    <head>
        <meta charset="utf-8">

        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>
        <?php echo $this->headScript() ?>
        
        <title>Module utilisateur | Connexion</title>
        
        <style>
          body {
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
          }

          .well {
            padding: 19px 29px 29px;
            margin: 0 auto 20px;
            background-color: #fff;
            border: 1px solid #e5e5e5;
            -webkit-border-radius: 5px;
               -moz-border-radius: 5px;
                    border-radius: 5px;
            -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
               -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                    box-shadow: 0 1px 2px rgba(0,0,0,.05);
          }
        </style>

        <!--<script src="/js/libs/modernizr-2.5.3.min.js"></script>-->
    </head>
    
    <body>
    
        <div class="container well">

            <!-- Notifications -->
            <?php if( $this->flashMessenger()->hasMessages() ): ?>
                <ul id="flashmessenger" class="unstyled" >
                <?php echo $this->flashMessenger()->output(); ?>
                </ul>
            <?php endif ?>
            
            <!-- Content -->
            <?php echo $this->layout()->content ?>

        </div>

        <!-- javascript (fast load)-->
        <?php echo $this->inlineScript() ?>
        
    </body>
    
</html>